# 10 most commonly used NumPy mathematical operations:

In [1]:
# Import NumPy library
import numpy as np


In [2]:

# Example 1: Array creation
print("1. Array Creation:")
a = np.array([1, 2, 3, 4, 5])
print("Array:", a)


1. Array Creation:
Array: [1 2 3 4 5]


In [3]:
# Example 2: Element-wise arithmetic operations
print("\n2. Element-wise Arithmetic Operations:")
b = np.array([6, 7, 8, 9, 10])
print("array1: ",a)

print("array b: " ,b)



# Addition
print("Addition:", a + b)

# Subtraction
print("Subtraction:", a - b)

# Multiplication
print("Multiplication:", a * b)

# Division
print("Division:", a / b)




2. Element-wise Arithmetic Operations:
array1:  [1 2 3 4 5]
array b:  [ 6  7  8  9 10]
Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:

# Example 3: Array broadcasting
print("\n3. Array Broadcasting:")
c = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Array:")
print(c)

# Add scalar to array
print("Add Scalar to Array:")
print(c + 10)

# Multiply array by scalar
print("Multiply Array by Scalar:")
print(c * 2)



3. Array Broadcasting:
Original Array:
[[1 2 3]
 [4 5 6]]
Add Scalar to Array:
[[11 12 13]
 [14 15 16]]
Multiply Array by Scalar:
[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
c


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:

# Example 4: Array aggregation functions
print("\n4. Array Aggregation Functions:")
d = np.array([1, 2, 3, 4, 5])
print("Array:", d)

# Sum
print("Sum:", np.sum(d))

# Mean
print("Mean:", np.mean(d))

# Maximum
print("Maximum:", np.max(d))

# Minimum
print("Minimum:", np.min(d))



4. Array Aggregation Functions:
Array: [1 2 3 4 5]
Sum: 15
Mean: 3.0
Maximum: 5
Minimum: 1


In [ ]:

# Example 5: Array manipulation functions
print("\n5. Array Manipulation Functions:")
e = np.array([[1, 2], [3, 4], [5, 6]])
print("Original Array:")
print(e)

# Transpose
print("Transpose:")
print(np.transpose(e))

# Reshape
print("Reshape:")
print(np.reshape(e, (2, 3)))

# Flatten
print("Flatten:")
print(e.flatten())


5. Array Manipulation Functions:
Original Array:
[[1 2]
 [3 4]
 [5 6]]
Transpose:
[[1 3 5]
 [2 4 6]]
Reshape:
[[1 2 3]
 [4 5 6]]
Flatten:
[1 2 3 4 5 6]


In [ ]:
ar  = np.arange(1,13).reshape(2,3,2)
print(ar)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# Reshape
print("Reshape:")
print(np.reshape(ar, (2, 3,2)))

Reshape:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:

# Example 6: Array sorting
print("\n6. Array Sorting:")
f = np.array([5, 2, 9, 1, 7])
print("Original Array:", f)

# Sort array
print("Sorted Array:", np.sort(f))



6. Array Sorting:
Original Array: [5 2 9 1 7]
Sorted Array: [1 2 5 7 9]


In [ ]:

# Example 7: Linear algebra operations
print("\n7. Linear Algebra Operations:")
g = np.array([[1, 2], [3, 4]])
h = np.array([[5, 6], [7, 8]])

# Matrix multiplication
print("Matrix Multiplication:")
print(np.dot(g, h))






7. Linear Algebra Operations:
Matrix Multiplication:
[[19 22]
 [43 50]]


In [ ]:

# Example 8: Random number generation
print("\n8. Random Number Generation:")
# Generate random integers
print("Random Integers:", np.random.randint(1, 10, size=5))

# Generate random floats
print("Random Floats:", np.random.rand(5))



8. Random Number Generation:
Random Integers: [9 8 1 6 2]
Random Floats: [0.77553235 0.02286841 0.55924775 0.79719365 0.70223031]


In [ ]:

# Example 9: Trigonometric functions
print("\n9. Trigonometric Functions:")
i = np.array([0, np.pi/2, np.pi])
print("Array:", i)

# Sine
print("Sine:", np.sin(i))

# Cosine
print("Cosine:", np.cos(i))

# Tangent
print("Tangent:", np.tan(i))


9. Trigonometric Functions:
Array: [0.         1.57079633 3.14159265]
Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tangent: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:

# Example 10: Exponential and logarithmic functions
print("\n10. Exponential and Logarithmic Functions:")
j = np.array([1, 2, 3])
print("Array:", j)

# Exponential
print("Exponential:", np.exp(j))

# Natural logarithm
print("Natural Logarithm:", np.log(j))



10. Exponential and Logarithmic Functions:
Array: [1 2 3]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Natural Logarithm: [0.         0.69314718 1.09861229]
