# Broadcasting in NumPy

Broadcasting allows NumPy to perform element-wise operations on arrays of different shapes.
This notebook demonstrates the concept of broadcasting with various examples.

In [ ]:
import numpy as np

## Example 1: Adding a scalar to an array
When a scalar is added to an array, the scalar is "broadcast" to match the shape of the array.
This means the scalar is treated as if it were an array of the same shape, filled with the scalar's value.

In [ ]:
a = np.array([1, 2, 3])
print("Original array:", a)
print("Scalar to add: 5")
b = a + 5
print("Resulting array:", b)

Original array: [1 2 3]
Scalar to add: 5
Resulting array: [6 7 8]


## Example 2: Adding arrays of different shapes
When two arrays have different shapes, broadcasting aligns their shapes.
In this example, array `b` is a 1D array and is broadcasted to match the shape of `a`, a 2D array.
Specifically, `b` is treated as if it were `[[10, 20, 30], [10, 20, 30]]`.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
print("Array a:\n", a)
print("Array b:\n", b)
result = a + b
print("Result:\n", result)

Array a:
 [[1 2 3]
 [4 5 6]]
Array b:
 [10 20 30]
Result:
 [[11 22 33]
 [14 25 36]]


## Example 3: Broadcasting with multidimensional arrays
Here, `a` is a column vector (3x1) and `b` is a row vector (1x3).
Broadcasting expands `a` to a 3x3 array by repeating its column values,
and `b` is expanded to a 3x3 array by repeating its row values.

In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print("Array a:\n", a)
print("Array b:\n", b)
result = a + b
print("Result:\n", result)

Array a:
 [[1]
 [2]
 [3]]
Array b:
 [10 20 30]
Result:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


## Example 4: Multiplying arrays with broadcasting
In this example, `a` is a 1D array (1x3) and `b` is a 2D array (3x1).
Broadcasting expands `a` to a 3x3 array by repeating its row values,
and `b` to a 3x3 array by repeating its column values.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[2], [4], [6]])
print("Array a:\n", a)
print("Array b:\n", b)
result = a * b
print("Result:\n", result)

Array a:
 [1 2 3]
Array b:
 [[2]
 [4]
 [6]]
Result:
 [[ 2  4  6]
 [ 4  8 12]
 [ 6 12 18]]


## Broadcasting Rules
1. If the arrays do not have the same dims, prepend the shape of the smaller array with ones until both shapes have the same length.
2. The size of each dimension is compared. Arrays are compatible if:
   - They are equal, or
   - One of them is 1.
3. If the arrays are compatible, broadcasting occurs.
4. If the arrays are not compatible, a `ValueError` is raised.

## Example 5: Broadcasting error
In this case, the shapes of the arrays are not compatible for broadcasting.
`a` has shape (3,) and `b` has shape (2,2), so their dimensions cannot be aligned.
This results in a `ValueError`.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
print("Array a:\n", a)
print("Array b:\n", b)
try:
    result = a + b
except ValueError as e:
    print("Error:", e)

Array a:
 [1 2 3]
Array b:
 [[1 2]
 [3 4]]
Error: operands could not be broadcast together with shapes (3,) (2,2) 
