# **Creating NumPy Arrays from Python Lists**





### **1. Creating a 1D NumPy Array**
A **1D array** (one-dimensional) is a simple list of elements.

```python
import numpy as np

# Creating a 1D NumPy array from a Python list
list_1d = [1, 2, 3, 4, 5]
array_1d = np.array(list_1d)

print("1D Array:")
print(array_1d)
```

**Output:**
```
1D Array:
[1 2 3 4 5]
```

---

## **2. Creating a 2D NumPy Array**
A **2D array** (two-dimensional) is like a matrix with rows and columns.

```python
# Creating a 2D NumPy array from a nested Python list
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_2d = np.array(list_2d)

print("2D Array:")
print(array_2d)
```

**Output:**
```
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

---

## **3. Creating a 3D NumPy Array**
A **3D array** (three-dimensional) is like multiple 2D arrays stacked together.

```python
# Creating a 3D NumPy array from a nested Python list
list_3d = [
    [[1, 2, 3], [4, 5, 6]],  # First 2D array
    [[7, 8, 9], [10, 11, 12]] # Second 2D array
]

array_3d = np.array(list_3d)

print("3D Array:")
print(array_3d)
```

**Output:**
```
3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
```

---

## **4. Checking the Shape of the Arrays**
To verify the dimensions of each array, you can use the `.shape` attribute:

```python
print("Shape of 1D array:", array_1d.shape)  # (5,)
print("Shape of 2D array:", array_2d.shape)  # (3, 3)
print("Shape of 3D array:", array_3d.shape)  # (2, 2, 3)
```

---

## **Summary**
| Array Type | Example Structure | Shape |
|------------|------------------|-------|
| **1D Array** | `[1, 2, 3, 4, 5]` | `(5,)` |
| **2D Array** | `[[1, 2, 3], [4, 5, 6], [7, 8, 9]]` | `(3, 3)` |
| **3D Array** | `[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]` | `(2, 2, 3)` |





# **Creating NumPy Arrays from Python Tuples**



## **1. Creating a 1D NumPy Array**
A **1D array** (one-dimensional) is a simple collection of elements.

```python
import numpy as np

# Creating a 1D NumPy array from a Python tuple
tuple_1d = (1, 2, 3, 4, 5)
array_1d = np.array(tuple_1d)

print("1D Array:")
print(array_1d)
```

**Output:**
```
1D Array:
[1 2 3 4 5]
```

---

## **2. Creating a 2D NumPy Array**
A **2D array** (two-dimensional) is like a matrix with rows and columns.

```python
# Creating a 2D NumPy array from a nested Python tuple
tuple_2d = ((1, 2, 3), (4, 5, 6), (7, 8, 9))
array_2d = np.array(tuple_2d)

print("2D Array:")
print(array_2d)
```

**Output:**
```
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

---

## **3. Creating a 3D NumPy Array**
A **3D array** (three-dimensional) is like multiple 2D arrays stacked together.

```python
# Creating a 3D NumPy array from a nested Python tuple
tuple_3d = (
    ((1, 2, 3), (4, 5, 6)),  # First 2D array
    ((7, 8, 9), (10, 11, 12)) # Second 2D array
)

array_3d = np.array(tuple_3d)

print("3D Array:")
print(array_3d)
```

**Output:**
```
3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
```

---

## **4. Checking the Shape of the Arrays**
To verify the dimensions of each array, you can use the `.shape` attribute:

```python
print("Shape of 1D array:", array_1d.shape)  # (5,)
print("Shape of 2D array:", array_2d.shape)  # (3, 3)
print("Shape of 3D array:", array_3d.shape)  # (2, 2, 3)
```

---

## **Summary**
| Array Type | Example Structure | Shape |
|------------|------------------|-------|
| **1D Array** | `(1, 2, 3, 4, 5)` | `(5,)` |
| **2D Array** | `((1, 2, 3), (4, 5, 6), (7, 8, 9))` | `(3, 3)` |
| **3D Array** | `(((1, 2, 3), (4, 5, 6)), ((7, 8, 9), (10, 11, 12)))` | `(2, 2, 3)` |



# **Creating NumPy Arrays Using `np.arange()`**




The `np.arange(start, stop, step)` function generates evenly spaced values within a given range.

---

### 1. Creating a 1D NumPy Array
A **1D array** can be created using `np.arange(start, stop, step)`, where:
- `start` is the starting value (inclusive),
- `stop` is the ending value (exclusive),
- `step` is the interval between values.

```python
import numpy as np

# Creating a 1D NumPy array using np.arange()
array_1d = np.arange(1, 11, 2)  # Start at 1, go up to 10 (exclusive), step by 2

print("1D Array:")
print(array_1d)
```

**Output:**
```
1D Array:
[ 1  3  5  7  9]
```

---

### 2. Creating a 2D NumPy Array
A **2D array** can be created by reshaping a 1D array.

```python
# Creating a 2D NumPy array using np.arange() and reshaping it
array_2d = np.arange(1, 10).reshape(3, 3)  # Reshape into a 3x3 matrix

print("2D Array:")
print(array_2d)
```

**Output:**
```
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

---

### 3. Creating a 3D NumPy Array
A **3D array** can be created by reshaping a 1D array.

```python
# Creating a 3D NumPy array using np.arange() and reshaping it
array_3d = np.arange(1, 13).reshape(2, 2, 3)  # Reshape into a 2x2x3 array

print("3D Array:")
print(array_3d)
```

**Output:**
```
3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
```

---

### 4. Checking the Shape of the Arrays
To verify the dimensions of each array, use the `.shape` attribute:

```python
print("Shape of 1D array:", array_1d.shape)  # (5,)
print("Shape of 2D array:", array_2d.shape)  # (3, 3)
print("Shape of 3D array:", array_3d.shape)  # (2, 2, 3)
```

---

### Summary
| Array Type | Example `np.arange()` Usage | Shape |
|------------|---------------------------|-------|
| **1D Array** | `np.arange(1, 11, 2)` | `(5,)` |
| **2D Array** | `np.arange(1, 10).reshape(3, 3)` | `(3, 3)` |
| **3D Array** | `np.arange(1, 13).reshape(2, 2, 3)` | `(2, 2, 3)` |


# Creating NumPy Arrays Using `np.linspace()`




The `np.linspace(start, stop, num=50, endpoint=True, retstep=False)` function generates **evenly spaced** numbers over a specified range.

## Parameters:
- `start`: The starting value (inclusive).
- `stop`: The ending value (inclusive by default).
- `num` (default=50): The number of values to generate.
- `endpoint` (default=True): If `True`, the `stop` value is included. If `False`, it is excluded.
- `retstep` (default=False): If `True`, the function also returns the step size between values.

---

### 1. Understanding the `num` Parameter
By default, `np.linspace()` generates `50` values. We can specify a different number of values.

```python
import numpy as np

# Using the default num=50
array_default = np.linspace(1, 10)  # Default num=50

# Using a custom num value
array_custom = np.linspace(1, 10, 5)  # Generates 5 values

print("Default num=50, First 5 values:", array_default[:5])
print("Custom num=5:", array_custom)
```

**Output:**
```
Default num=50, First 5 values: [1.   1.18 1.37 1.55 1.73]
Custom num=5: [ 1.   3.25  5.5   7.75 10.  ]
```

---

### 2. Understanding the `endpoint` Parameter
By default, `endpoint=True`, meaning the `stop` value is included. If `endpoint=False`, the `stop` value is **excluded**, and values are spaced accordingly.

```python
# With endpoint=True (default)
array_with_endpoint = np.linspace(1, 10, 5, endpoint=True)

# With endpoint=False (excludes the stop value)
array_without_endpoint = np.linspace(1, 10, 5, endpoint=False)

print("With endpoint=True:", array_with_endpoint)
print("With endpoint=False:", array_without_endpoint)
```

**Output:**
```
With endpoint=True: [ 1.   3.25  5.5   7.75 10.  ]
With endpoint=False: [1.  2.8 4.6 6.4 8.2]
```

---

### 3. Understanding the `retstep` Parameter
If `retstep=True`, `np.linspace()` returns both the array and the step size between consecutive values.

```python
# Using retstep=True to get the step size
array_with_step, step = np.linspace(1, 10, 5, retstep=True)

print("Array:", array_with_step)
print("Step size:", step)
```

**Output:**
```
Array: [ 1.   3.25  5.5   7.75 10.  ]
Step size: 2.25
```

---

### 4. Creating 1D, 2D, and 3D Arrays Using `np.linspace()`

#### **1D Array**
```python
array_1d = np.linspace(1, 10, 5)
print("1D Array:", array_1d)
```

**Output:**
```
1D Array: [ 1.   3.25  5.5   7.75 10.  ]
```

---

#### **2D Array**
```python
array_2d = np.linspace(1, 9, 9).reshape(3, 3)
print("2D Array:\n", array_2d)
```

**Output:**
```
2D Array:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
```

---

#### **3D Array**
```python
array_3d = np.linspace(1, 12, 12).reshape(2, 2, 3)
print("3D Array:\n", array_3d)
```

**Output:**
```
3D Array:
[[[ 1.   2.1  3.2]
  [ 4.3  5.4  6.5]]

 [[ 7.6  8.7  9.8]
  [10.9 12.  13.1]]]
```

---

### Summary Table
| Parameter | Description | Example |
|-----------|-------------|---------|
| **`num`** | Defines the number of elements (default=50) | `np.linspace(1, 10, num=5)` |
| **`endpoint`** | Includes `stop` value if `True`, excludes it if `False` | `np.linspace(1, 10, 5, endpoint=False)` |
| **`retstep`** | Returns step size if `True` | `np.linspace(1, 10, 5, retstep=True)` |


# Creating NumPy Arrays Using `ones`, `zeros`, and `empty`
------------------------------------------------



NumPy provides three useful functions to create arrays filled with **ones**, **zeros**, or **uninitialized values**:

- `np.ones(shape)`: Creates an array filled with `1`s.
- `np.zeros(shape)`: Creates an array filled with `0`s.
- `np.empty(shape)`: Creates an array without initializing values (values may be random).

---

### 1. Creating Arrays Using `np.ones()`
The `np.ones(shape, dtype)` function creates an array filled with `1`s.

```python
import numpy as np

# 1D array of ones
array_1d = np.ones(5)

# 2D array of ones
array_2d = np.ones((3, 3))

# 3D array of ones
array_3d = np.ones((2, 2, 3))

print("1D Array:\n", array_1d)
print("2D Array:\n", array_2d)
print("3D Array:\n", array_3d)
```

**Output:**
```
1D Array:
 [1. 1. 1. 1. 1.]

2D Array:
 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

3D Array:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
```

---

### 2. Creating Arrays Using `np.zeros()`
The `np.zeros(shape, dtype)` function creates an array filled with `0`s.

```python
# 1D array of zeros
array_1d = np.zeros(5)

# 2D array of zeros
array_2d = np.zeros((3, 3))

# 3D array of zeros
array_3d = np.zeros((2, 2, 3))

print("1D Array:\n", array_1d)
print("2D Array:\n", array_2d)
print("3D Array:\n", array_3d)
```

**Output:**
```
1D Array:
 [0. 0. 0. 0. 0.]

2D Array:
 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

3D Array:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
```

---

### 3. Creating Arrays Using `np.empty()`
The `np.empty(shape, dtype)` function creates an array without initializing values, meaning the values may be random (leftover from memory).

```python
# 1D empty array
array_1d = np.empty(5)

# 2D empty array
array_2d = np.empty((3, 3))

# 3D empty array
array_3d = np.empty((2, 2, 3))

print("1D Array:\n", array_1d)
print("2D Array:\n", array_2d)
print("3D Array:\n", array_3d)
```

**Output (values may vary since it's uninitialized memory):**
```
1D Array:
 [1.39064994e-309 1.39064994e-309 1.39064994e-309 1.39064994e-309 1.39064994e-309]

2D Array:
 [[6.79038654e-313 2.14321575e-312 2.46151512e-312]
  [2.41907520e-312 2.56761491e-312 2.14321575e-312]
  [2.22809558e-312 2.35541533e-312 2.35541533e-312]]

3D Array:
 [[[1.48219694e-323 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]]]
```
💡 *Note: `np.empty()` does not initialize the array with any specific values, so its contents will be arbitrary.*

---

### 4. Specifying `dtype` (Data Type)
You can specify the data type (`dtype`) while creating arrays.

```python
# Integer ones array
int_ones = np.ones((2, 2), dtype=int)

# Float zeros array
float_zeros = np.zeros((2, 2), dtype=float)

print("Integer Ones Array:\n", int_ones)
print("Float Zeros Array:\n", float_zeros)
```

**Output:**
```
Integer Ones Array:
 [[1 1]
  [1 1]]

Float Zeros Array:
 [[0. 0.]
  [0. 0.]]
```

---

### Summary Table
| Function | Description | Example |
|----------|-------------|---------|
| `np.ones(shape)` | Creates an array filled with `1`s | `np.ones((3,3))` |
| `np.zeros(shape)` | Creates an array filled with `0`s | `np.zeros((3,3))` |
| `np.empty(shape)` | Creates an array without initialization (random values) | `np.empty((3,3))` |



# Creating NumPy Arrays Using `full`



The `np.full(shape, fill_value, dtype=None)` function creates a NumPy array with a specified shape and fills it with a constant value.

### Syntax:
```python
np.full(shape, fill_value, dtype=None)
```
- **shape**: Specifies the dimensions of the array.
- **fill_value**: The constant value to fill the array with.
- **dtype** (optional): Defines the data type of the array.

---

### 1. Creating a 1D Array Using `np.full()`
```python
import numpy as np

# Creating a 1D array filled with 7
array_1d = np.full(5, 7)

print("1D Array:\n", array_1d)
```
**Output:**
```
1D Array:
 [7 7 7 7 7]
```

---

### 2. Creating a 2D Array Using `np.full()`
```python
# Creating a 2D array filled with -3
array_2d = np.full((3, 3), -3)

print("2D Array:\n", array_2d)
```
**Output:**
```
2D Array:
 [[-3 -3 -3]
  [-3 -3 -3]
  [-3 -3 -3]]
```

---

### 3. Creating a 3D Array Using `np.full()`
```python
# Creating a 3D array filled with 9.99
array_3d = np.full((2, 2, 3), 9.99)

print("3D Array:\n", array_3d)
```
**Output:**
```
3D Array:
 [[[9.99 9.99 9.99]
  [9.99 9.99 9.99]]

 [[9.99 9.99 9.99]
  [9.99 9.99 9.99]]]
```

---

### 4. Specifying `dtype` While Using `np.full()`
You can explicitly set the data type of the array using the `dtype` parameter.

```python
# Creating an integer array filled with 5
array_int = np.full((2, 2), 5, dtype=int)

# Creating a float array filled with 2.5
array_float = np.full((2, 2), 2.5, dtype=float)

print("Integer Array:\n", array_int)
print("Float Array:\n", array_float)
```
**Output:**
```
Integer Array:
 [[5 5]
  [5 5]]

Float Array:
 [[2.5 2.5]
  [2.5 2.5]]
```

---

### Summary Table
| Function | Description | Example |
|----------|-------------|---------|
| `np.full(shape, value)` | Creates an array filled with a specified value | `np.full((3,3), 10)` |
| `np.full(shape, value, dtype=int)` | Creates an array with a specified data type | `np.full((2,2), -1, dtype=int)` |

Using `np.full()` is useful when you need an array with a predefined value instead of zeros or ones. 🚀

---



# Creating NumPy Arrays Using `eye` and `identity`



NumPy provides two functions, `np.eye()` and `np.identity()`, to create identity matrices (matrices with ones on the main diagonal and zeros elsewhere).

---

### 1. Creating an Identity Matrix Using `np.eye()`

The `np.eye(N, M=None, k=0, dtype=float)` function creates a 2D identity-like matrix with ones on the diagonal and zeros elsewhere.

#### Parameters:
- **N**: Number of rows.
- **M** *(optional)*: Number of columns (defaults to `N`).
- **k** *(optional)*: Diagonal offset (`0` for main diagonal, positive for above, negative for below).
- **dtype** *(optional)*: Data type of the array.

```python
import numpy as np

# Creating a 3x3 identity matrix
matrix_eye = np.eye(3)

print("3x3 Identity Matrix using np.eye():\n", matrix_eye)
```

**Output:**
```
3x3 Identity Matrix using np.eye():
 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]
```

---

### 2. Creating a Non-Square Matrix Using `np.eye()`
You can specify a different number of columns to create a non-square matrix.

```python
# Creating a 3x4 matrix with ones on the diagonal
matrix_eye_rectangular = np.eye(3, 4)

print("3x4 Matrix using np.eye():\n", matrix_eye_rectangular)
```

**Output:**
```
3x4 Matrix using np.eye():
 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]
```

---

### 3. Using the `k` Parameter in `np.eye()`
The `k` parameter shifts the diagonal.

```python
# Upper diagonal (k=1)
matrix_eye_upper = np.eye(4, k=1)

# Lower diagonal (k=-1)
matrix_eye_lower = np.eye(4, k=-1)

print("Upper Diagonal (k=1):\n", matrix_eye_upper)
print("\nLower Diagonal (k=-1):\n", matrix_eye_lower)
```

**Output:**
```
Upper Diagonal (k=1):
 [[0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [0. 0. 0. 0.]]

Lower Diagonal (k=-1):
 [[0. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]
```

---

### 4. Creating an Identity Matrix Using `np.identity()`

The `np.identity(N, dtype=float)` function creates a **square identity matrix** (unlike `eye()`, it does not accept `M` or `k`).

```python
# Creating a 4x4 identity matrix
matrix_identity = np.identity(4)

print("4x4 Identity Matrix using np.identity():\n", matrix_identity)
```

**Output:**
```
4x4 Identity Matrix using np.identity():
 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]
```

---

### 5. Difference Between `np.eye()` and `np.identity()`
| Function | Description | Example |
|----------|-------------|---------|
| `np.eye(N, M=None, k=0)` | Creates an identity-like matrix with optional shape and diagonal shift | `np.eye(3, 4, k=1)` |
| `np.identity(N)` | Creates a square identity matrix (only accepts `N`) | `np.identity(4)` |

---

### Summary:
- Use **`np.eye()`** when you need a **custom-sized identity-like matrix** (rectangular or shifted diagonals).
- Use **`np.identity()`** when you need a **simple square identity matrix**.



# Creating NumPy Arrays Using `random`, `random.random`, `rand`, `randn`, and `randint`



NumPy provides a powerful random number generation module called `numpy.random`, which allows us to generate random numbers from different distributions.

---

### 1. Using `np.random.random()`
The `np.random.random(size)` function generates an array of random floating-point numbers between `0` and `1`.

```python
import numpy as np

# Generate a 1D array of 5 random values
array_random = np.random.random(5)

print("1D Array using np.random.random():\n", array_random)
```

**Output Example:**
```
1D Array using np.random.random():
 [0.3214 0.8756 0.2345 0.6789 0.4567]
```

- **size**: Defines the shape of the output array (if omitted, a single value is returned).

---

### 2. Using `np.random.rand()`
The `np.random.rand(d0, d1, ..., dn)` function generates an array of random values between `0` and `1`, but allows specifying multiple dimensions directly.

```python
# Generate a 2x3 matrix of random values
array_rand = np.random.rand(2, 3)

print("2D Array using np.random.rand():\n", array_rand)
```

**Output Example:**
```
2D Array using np.random.rand():
 [[0.1234 0.5678 0.9876]
  [0.5432 0.6789 0.3214]]
```

---

### 3. Using `np.random.randn()`
The `np.random.randn(d0, d1, ..., dn)` function generates random numbers **from a standard normal distribution** (mean = 0, variance = 1).

```python
# Generate a 3x3 matrix of standard normally distributed random values
array_randn = np.random.randn(3, 3)

print("3x3 Array using np.random.randn():\n", array_randn)
```

**Output Example:**
```
3x3 Array using np.random.randn():
 [[ 0.1234 -0.5678  0.9876]
  [-1.2345  0.5432 -0.6789]
  [ 0.8765 -0.4321  1.2345]]
```

- Values are **not** restricted to [0,1] but follow a normal distribution.

---

### 4. Using `np.random.randint()`
The `np.random.randint(low, high=None, size=None, dtype=int)` function generates random integers within a specified range.

```python
# Generate a 4x4 matrix of random integers between 10 and 50
array_randint = np.random.randint(10, 50, (4, 4))

print("4x4 Array using np.random.randint():\n", array_randint)
```

**Output Example:**
```
4x4 Array using np.random.randint():
 [[15 23 47 38]
  [11 42 33 29]
  [39 26 18 41]
  [32 19 12 46]]
```

- If `high` is omitted, numbers are generated from `0` to `low`.
- `size` specifies the shape of the output array.

---

### 5. Summary Table

| Function | Description | Example |
|----------|-------------|---------|
| `np.random.random(size)` | Generates random floats in [0,1) | `np.random.random((3,2))` |
| `np.random.rand(d0, d1, ...)` | Generates uniform random floats in [0,1) | `np.random.rand(2,3)` |
| `np.random.randn(d0, d1, ...)` | Generates normally distributed random values | `np.random.randn(3,3)` |
| `np.random.randint(low, high, size)` | Generates random integers in a given range | `np.random.randint(10, 50, (4,4))` |

---

### Summary:
- Use **`random.random()`** or **`rand()`** for uniform random values between `0` and `1`.
- Use **`randn()`** for normal distribution (bell curve) values.
- Use **`randint()`** for generating random integers within a specific range.


# Creating NumPy Arrays Using `astype` to Specify Data Types




NumPy provides the `astype()` method to **convert the data type** of an array explicitly. This is useful when dealing with memory optimization, type compatibility, or precision control.

---

### 1. What is `astype()`?
The `astype(dtype)` method is used to **convert the data type** of a NumPy array to a specified type.

#### Syntax:
```python
array.astype(new_dtype)
```

- `new_dtype`: The desired data type (e.g., `int`, `float`, `bool`, `complex`, etc.).
- The original array remains unchanged; `astype()` returns a **new array**.

---

### 2. Converting an Array to `int`
Let's create an array of floating-point numbers and convert it into integers.

```python
import numpy as np

# Creating a NumPy array of floats
arr_float = np.array([1.5, 2.8, 3.9, 4.2])

# Converting to integers
arr_int = arr_float.astype(int)

print("Original Float Array:\n", arr_float)
print("Converted Integer Array:\n", arr_int)
```

**Output:**
```
Original Float Array:
 [1.5 2.8 3.9 4.2]

Converted Integer Array:
 [1 2 3 4]
```
- The decimal values are truncated (not rounded) when converting to integers.

---

### 3. Converting an Array to `float`
```python
# Creating an array of integers
arr_int = np.array([1, 2, 3, 4])

# Converting to float
arr_float = arr_int.astype(float)

print("Integer Array:\n", arr_int)
print("Converted Float Array:\n", arr_float)
```

**Output:**
```
Integer Array:
 [1 2 3 4]

Converted Float Array:
 [1. 2. 3. 4.]
```

- The integers are converted into floating-point numbers with a `.0` suffix.

---

### 4. Converting an Array to `bool`
```python
# Creating an array with integers
arr = np.array([0, 1, 2, 0, -3, 4])

# Converting to boolean
arr_bool = arr.astype(bool)

print("Original Array:\n", arr)
print("Converted Boolean Array:\n", arr_bool)
```

**Output:**
```
Original Array:
 [ 0  1  2  0 -3  4]

Converted Boolean Array:
 [False  True  True False  True  True]
```
- `0` converts to `False`, while all **non-zero** values convert to `True`.

---

### 5. Converting an Array to `complex`
```python
# Creating an integer array
arr = np.array([1, 2, 3, 4])

# Converting to complex
arr_complex = arr.astype(complex)

print("Integer Array:\n", arr)
print("Converted Complex Array:\n", arr_complex)
```

**Output:**
```
Integer Array:
 [1 2 3 4]

Converted Complex Array:
 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]
```
- Each element gets a complex part (`+0.j`).

---

### 6. Using `astype()` with String Conversion
```python
# Creating a NumPy array of integers
arr = np.array([10, 20, 30])

# Converting to string
arr_str = arr.astype(str)

print("Integer Array:\n", arr)
print("Converted String Array:\n", arr_str)
```

**Output:**
```
Integer Array:
 [10 20 30]

Converted String Array:
 ['10' '20' '30']
```

- Each number is now stored as a string.

---

### 7. Summary Table

| Conversion | Syntax | Example |
|------------|--------|---------|
| Float to Integer | `arr.astype(int)` | `np.array([1.5, 2.8]).astype(int)` → `[1, 2]` |
| Integer to Float | `arr.astype(float)` | `np.array([1, 2, 3]).astype(float)` → `[1.0, 2.0, 3.0]` |
| Integer to Boolean | `arr.astype(bool)` | `np.array([0, 1, -2]).astype(bool)` → `[False, True, True]` |
| Integer to Complex | `arr.astype(complex)` | `np.array([1, 2]).astype(complex)` → `[1.+0.j, 2.+0.j]` |
| Integer to String | `arr.astype(str)` | `np.array([10, 20]).astype(str)` → `['10', '20']` |

---

### Summary:
- `astype()` is useful for **changing data types** in NumPy arrays.
- It **does not modify** the original array but returns a **new one**.
- Be cautious of **data loss** when converting between types (e.g., float to int truncation).



# Creating a New NumPy Array Using `reshape`



The `reshape()` function in NumPy allows us to **change the shape** of an existing array without modifying its data. It is useful when we need to convert a **1D array into a 2D or 3D structure** while maintaining the same number of elements.

---

### 1. Understanding `reshape()`
#### Syntax:
```python
array.reshape(new_shape)
```
- `new_shape`: A tuple defining the desired shape.
- The number of elements in `new_shape` must match the original array.

---

### 2. Reshaping a 1D Array to a 2D Array
We can reshape a 1D array into a 2D matrix by specifying rows and columns.

```python
import numpy as np

# Creating a 1D array of 6 elements
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshaping to a 2D array (2 rows, 3 columns)
arr_2d = arr_1d.reshape(2, 3)

print("Original 1D Array:\n", arr_1d)
print("Reshaped 2D Array:\n", arr_2d)
```

**Output:**
```
Original 1D Array:
 [1 2 3 4 5 6]

Reshaped 2D Array:
 [[1 2 3]
  [4 5 6]]
```
- The original **1D array** with 6 elements is reshaped into a **2×3 matrix**.

---

### 3. Reshaping a 1D Array to a 3D Array
We can also reshape a 1D array into a **3D array** by specifying depth, rows, and columns.

```python
# Creating a 1D array of 12 elements
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshaping into a 3D array (2 blocks, 2 rows, 3 columns)
arr_3d = arr_1d.reshape(2, 2, 3)

print("Reshaped 3D Array:\n", arr_3d)
```

**Output:**
```
Reshaped 3D Array:
 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]
```
- The **1D array** is reshaped into **two 2×3 matrices** stacked together.

---

### 4. Using `-1` to Let NumPy Calculate Shape Automatically
Instead of manually specifying all dimensions, we can use `-1` to let NumPy **infer the correct dimension**.

```python
# Reshaping a 1D array into a 2D array with 3 columns
arr_auto = arr_1d.reshape(-1, 3)

print("Reshaped Using -1:\n", arr_auto)
```

**Output:**
```
Reshaped Using -1:
 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]
```
- Here, `-1` lets NumPy **automatically determine the number of rows** while keeping 3 columns.

---

### 5. Reshaping a 2D Array to 1D (Flattening)
We can also **reshape a 2D or 3D array back into 1D**.

```python
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Flattening to 1D
arr_flattened = arr_2d.reshape(-1)

print("Flattened 1D Array:\n", arr_flattened)
```

**Output:**
```
Flattened 1D Array:
 [1 2 3 4 5 6]
```
- The **2D array** is converted back to **1D**.

---

### 6. Summary Table

| Reshaping Action | Syntax | Example |
|------------------|--------|---------|
| 1D → 2D | `array.reshape(rows, cols)` | `np.arange(6).reshape(2,3)` |
| 1D → 3D | `array.reshape(depth, rows, cols)` | `np.arange(12).reshape(2,2,3)` |
| Use `-1` | `array.reshape(-1, cols)` | `np.arange(12).reshape(-1,3)` |
| Flattening (2D to 1D) | `array.reshape(-1)` | `np.array([[1,2],[3,4]]).reshape(-1)` |

---

### Summary:
- **`reshape()`** allows changing the structure of an array while keeping its data intact.
- The total number of elements **must remain the same** before and after reshaping.
- Using **`-1`** lets NumPy infer the missing dimension automatically.
- We can reshape arrays into **1D, 2D, or 3D** as needed.



# Using `tile` to Repeat Arrays



The `np.tile()` function in NumPy is used to **repeat** an array along specified dimensions. It is useful when we need to duplicate an array multiple times in a structured manner.

---

### 1. Understanding `tile()`
#### Syntax:
```python
np.tile(A, reps)
```
- `A`: The input array to be repeated.
- `reps`: A tuple specifying how many times the array should be repeated along each axis.

---

### 2. Repeating a 1D Array
We can repeat a 1D array multiple times along its only dimension.

```python
import numpy as np

# Creating a 1D array
arr_1d = np.array([1, 2, 3])

# Repeating the array 3 times
tiled_1d = np.tile(arr_1d, 3)

print("Original 1D Array:", arr_1d)
print("Tiled 1D Array:", tiled_1d)
```

**Output:**
```
Original 1D Array: [1 2 3]
Tiled 1D Array: [1 2 3 1 2 3 1 2 3]
```
- The **1D array** `[1, 2, 3]` is repeated **3 times** in a row.

---

### 3. Repeating a 2D Array Along Both Axes
We can repeat a **2D array** along both rows and columns.

```python
# Creating a 2D array
arr_2d = np.array([[1, 2], [3, 4]])

# Repeating the array (2 times along rows, 3 times along columns)
tiled_2d = np.tile(arr_2d, (2, 3))

print("Original 2D Array:\n", arr_2d)
print("Tiled 2D Array:\n", tiled_2d)
```

**Output:**
```
Original 2D Array:
 [[1 2]
  [3 4]]

Tiled 2D Array:
 [[1 2 1 2 1 2]
  [3 4 3 4 3 4]
  [1 2 1 2 1 2]
  [3 4 3 4 3 4]]
```
- The array is **repeated twice along rows** and **three times along columns**.

---

### 4. Repeating a 3D Array
We can also apply `tile()` to a **3D array**.

```python
# Creating a 3D array
arr_3d = np.array([[[1, 2]], [[3, 4]]])

# Repeating the array (2 times along depth, 2 times along rows, 2 times along columns)
tiled_3d = np.tile(arr_3d, (2, 2, 2))

print("Original 3D Array:\n", arr_3d)
print("Tiled 3D Array:\n", tiled_3d)
```

**Output:**
```
Original 3D Array:
 [[[1 2]]
  [[3 4]]]

Tiled 3D Array:
 [[[1 2 1 2]
   [1 2 1 2]]

  [[3 4 3 4]
   [3 4 3 4]]

  [[1 2 1 2]
   [1 2 1 2]]

  [[3 4 3 4]
   [3 4 3 4]]]
```
- The **depth, rows, and columns** are all repeated according to the specified `(2, 2, 2)` pattern.

---

### 5. Difference Between `tile()` and `repeat()`
| Function | Behavior |
|----------|----------|
| `tile()` | Repeats the entire array as a block |
| `repeat()` | Repeats elements individually along an axis |

Example:
```python
arr = np.array([1, 2, 3])

# Using tile
print(np.tile(arr, 2))  # [1 2 3 1 2 3]

# Using repeat
print(np.repeat(arr, 2))  # [1 1 2 2 3 3]
```

---

### 6. Summary Table

| Scenario | Code | Example Output |
|----------|------|---------------|
| Repeat a 1D array 3 times | `np.tile([1,2,3], 3)` | `[1 2 3 1 2 3 1 2 3]` |
| Repeat a 2D array (rows × cols) | `np.tile([[1,2],[3,4]], (2,3))` | `[[1 2 1 2 1 2] [3 4 3 4 3 4] [1 2 1 2 1 2] [3 4 3 4 3 4]]` |
| Repeat a 3D array | `np.tile(arr, (2,2,2))` | `Expands depth, rows, and columns` |

---

### Summary:
- **`tile()`** duplicates an array **as a whole** along specified dimensions.
- Works for **1D, 2D, and 3D arrays**.
- The **shape of the repeated array depends on `reps`**.
- Different from **`repeat()`**, which repeats **individual elements** instead of the entire array.



# Using `fromfunction` to Create Arrays




The `np.fromfunction()` method in NumPy allows us to **generate arrays dynamically** by applying a function to each coordinate of the array.

---

### 1. Understanding `fromfunction()`
#### Syntax:
```python
np.fromfunction(function, shape, dtype=float, *, like=None)
```
- `function`: A function that takes as many arguments as the array dimensions and returns the corresponding values.
- `shape`: A tuple specifying the shape of the output array.
- `dtype`: The data type of the resulting array (default is `float`).

---

### 2. Creating a Simple 2D Array

```python
import numpy as np

# Function to generate values based on indices
def func(x, y):
    return x + y

# Creating a 2D array of shape (3, 3)
arr = np.fromfunction(func, (3, 3), dtype=int)

print("Generated 2D Array:\n", arr)
```

**Output:**
```
Generated 2D Array:
 [[0 1 2]
  [1 2 3]
  [2 3 4]]
```
- Each element is generated using `func(x, y) = x + y`, where `x` and `y` are the row and column indices.

---

### 3. Creating a Multiplication Table
We can use `fromfunction()` to create a **multiplication table**.

```python
def multiply(x, y):
    return (x + 1) * (y + 1)

# Creating a 5x5 multiplication table
multiplication_table = np.fromfunction(multiply, (5, 5), dtype=int)

print("5x5 Multiplication Table:\n", multiplication_table)
```

**Output:**
```
5x5 Multiplication Table:
 [[ 1  2  3  4  5]
  [ 2  4  6  8 10]
  [ 3  6  9 12 15]
  [ 4  8 12 16 20]
  [ 5 10 15 20 25]]
```
- The function `multiply(x, y) = (x+1) * (y+1)` generates a standard multiplication table.

---

### 4. Creating a 3D Array
We can also use `fromfunction()` to create a **3D array**.

```python
def three_d(x, y, z):
    return x + y * z

# Creating a 3D array of shape (3, 3, 3)
arr_3d = np.fromfunction(three_d, (3, 3, 3), dtype=int)

print("Generated 3D Array:\n", arr_3d)
```

**Output:**
```
Generated 3D Array:
 [[[0 0 0]
   [0 1 2]
   [0 2 4]]

  [[1 1 1]
   [1 2 3]
   [1 3 5]]

  [[2 2 2]
   [2 3 4]
   [2 4 6]]]
```
- Each element is calculated using `three_d(x, y, z) = x + y * z`.

---

### 5. Using `fromfunction()` with a Boolean Function
We can generate **Boolean masks** using `fromfunction()`.

```python
def is_even(x, y):
    return (x + y) % 2 == 0

# Creating a 5x5 boolean mask
bool_mask = np.fromfunction(is_even, (5, 5), dtype=int)

print("Boolean Mask Array:\n", bool_mask)
```

**Output:**
```
Boolean Mask Array:
 [[1 0 1 0 1]
  [0 1 0 1 0]
  [1 0 1 0 1]
  [0 1 0 1 0]
  [1 0 1 0 1]]
```
- The function `is_even(x, y) = (x + y) % 2 == 0` generates a **checkerboard pattern**.

---

### 6. Summary Table

| Use Case | Code Example | Output Example |
|----------|-------------|----------------|
| Create a simple 2D array | `np.fromfunction(lambda x, y: x + y, (3, 3), dtype=int)` | `[[0 1 2] [1 2 3] [2 3 4]]` |
| Create a multiplication table | `np.fromfunction(lambda x, y: (x+1) * (y+1), (5, 5), dtype=int)` | `[[1 2 3 4 5] [2 4 6 8 10] ...]` |
| Create a 3D array | `np.fromfunction(lambda x, y, z: x + y * z, (3, 3, 3), dtype=int)` | Expands across depth |
| Create a Boolean mask | `np.fromfunction(lambda x, y: (x+y) % 2 == 0, (5, 5), dtype=int)` | Generates a checkerboard pattern |

---

### Summary:
- **`fromfunction()`** dynamically **generates** arrays using a function.
- Works for **1D, 2D, and 3D arrays**.
- Useful for **index-based array creation**.
- Can be applied for **mathematical calculations, Boolean masks, and structured patterns**.



# Using `fromiter` to Create Arrays



The `np.fromiter()` method in NumPy allows us to **create a NumPy array from an iterable**, such as a list, tuple, or generator.

---

### 1. Understanding `fromiter()`
#### Syntax:
```python
np.fromiter(iterable, dtype, count=-1)
```
- `iterable`: Any iterable object (e.g., list, tuple, generator).
- `dtype`: Data type of the output array.
- `count`: Number of items to read from the iterable (`-1` means read all).

---

### 2. Creating an Array from a List
We can use `fromiter()` to create a NumPy array from a **list**.

```python
import numpy as np

# Creating a list
my_list = [1, 2, 3, 4, 5]

# Creating a NumPy array from the list
arr = np.fromiter(my_list, dtype=int)

print("NumPy Array:\n", arr)
```

**Output:**
```
NumPy Array:
 [1 2 3 4 5]
```
- The list `[1, 2, 3, 4, 5]` is converted into a NumPy array.

---

### 3. Creating an Array from a Tuple
We can also use `fromiter()` to create an array from a **tuple**.

```python
# Creating a tuple
my_tuple = (10, 20, 30, 40)

# Creating a NumPy array from the tuple
arr = np.fromiter(my_tuple, dtype=int)

print("NumPy Array from Tuple:\n", arr)
```

**Output:**
```
NumPy Array from Tuple:
 [10 20 30 40]
```
- The tuple `(10, 20, 30, 40)` is converted into a NumPy array.

---

### 4. Creating an Array from a Generator
We can use a **generator function** with `fromiter()` to create an array dynamically.

```python
# Generator function to yield squares of numbers
def squares(n):
    for i in range(n):
        yield i ** 2

# Creating a NumPy array from the generator
arr = np.fromiter(squares(5), dtype=int)

print("NumPy Array from Generator:\n", arr)
```

**Output:**
```
NumPy Array from Generator:
 [ 0  1  4  9 16]
```
- The generator yields squares of numbers (`0, 1, 4, 9, 16`), which are stored in a NumPy array.

---

### 5. Using `count` Parameter
The `count` parameter specifies the **number of elements** to read from the iterable.

```python
# Creating an iterable
iterable = iter(range(10))  # Iterable from 0 to 9

# Creating a NumPy array with only 5 elements
arr = np.fromiter(iterable, dtype=int, count=5)

print("NumPy Array with Limited Elements:\n", arr)
```

**Output:**
```
NumPy Array with Limited Elements:
 [0 1 2 3 4]
```
- Only the first `5` elements are read from the iterable.

---

### 6. Summary Table

| Use Case | Code Example | Output Example |
|----------|-------------|----------------|
| Create from a list | `np.fromiter([1, 2, 3, 4], dtype=int)` | `[1 2 3 4]` |
| Create from a tuple | `np.fromiter((10, 20, 30), dtype=int)` | `[10 20 30]` |
| Create from a generator | `np.fromiter((i**2 for i in range(5)), dtype=int)` | `[0 1 4 9 16]` |
| Limit elements with `count` | `np.fromiter(iter(range(10)), dtype=int, count=5)` | `[0 1 2 3 4]` |

---

### Summary:
- **`fromiter()`** is useful when working with **iterables, generators, and streams of data**.
- Works efficiently for **lazy evaluation**, avoiding storing large lists in memory.
- The **`count` parameter** limits the number of elements read.
- Ideal for processing **large datasets or streaming data**.


# Using `diag` to Create Arrays




The `np.diag()` function in NumPy is used to **extract the diagonal of a matrix** or **create a diagonal matrix from a given array**.

---

### 1. Understanding `diag()`
#### Syntax:
```python
np.diag(v, k=0)
```
- `v`: Can be a 1D array (to create a diagonal matrix) or a 2D matrix (to extract the diagonal elements).
- `k`: The diagonal offset.
  - `k=0` (default) → Main diagonal
  - `k>0` → Upper diagonals
  - `k<0` → Lower diagonals

---

### 2. Creating a Diagonal Matrix from a 1D Array
We can create a **diagonal matrix** where the input array appears along the main diagonal.

```python
import numpy as np

# 1D array
arr = np.array([1, 2, 3, 4])

# Creating a diagonal matrix
diag_matrix = np.diag(arr)

print("Diagonal Matrix:\n", diag_matrix)
```

**Output:**
```
Diagonal Matrix:
 [[1 0 0 0]
  [0 2 0 0]
  [0 0 3 0]
  [0 0 0 4]]
```
- The elements of `arr` appear along the **main diagonal**.

---

### 3. Creating a Diagonal Matrix with an Offset
We can shift the diagonal **above (`k>0`)** or **below (`k<0`)** the main diagonal.

```python
# Creating a diagonal matrix with k=1 (above the main diagonal)
diag_matrix_upper = np.diag(arr, k=1)

print("Diagonal Matrix with k=1:\n", diag_matrix_upper)
```

**Output:**
```
Diagonal Matrix with k=1:
 [[0 1 0 0 0]
  [0 0 2 0 0]
  [0 0 0 3 0]
  [0 0 0 0 4]
  [0 0 0 0 0]]
```
- The diagonal is **shifted one position** above the main diagonal.

Similarly, shifting **below the main diagonal** (`k=-1`):

```python
# Creating a diagonal matrix with k=-1 (below the main diagonal)
diag_matrix_lower = np.diag(arr, k=-1)

print("Diagonal Matrix with k=-1:\n", diag_matrix_lower)
```

**Output:**
```
Diagonal Matrix with k=-1:
 [[0 0 0 0]
  [1 0 0 0]
  [0 2 0 0]
  [0 0 3 0]
  [0 0 0 4]]
```
- The diagonal is **shifted one position** below the main diagonal.

---

### 4. Extracting the Diagonal from a 2D Matrix
If we pass a **2D square matrix** to `diag()`, it extracts its **main diagonal**.

```python
# 2D matrix
matrix = np.array([[5, 1, 3],
                   [2, 8, 4],
                   [7, 6, 9]])

# Extracting the main diagonal
main_diag = np.diag(matrix)

print("Extracted Main Diagonal:\n", main_diag)
```

**Output:**
```
Extracted Main Diagonal:
 [5 8 9]
```
- The elements `[5, 8, 9]` form the **main diagonal** of the matrix.

We can also extract **upper or lower diagonals** by specifying `k`.

```python
# Extracting the diagonal above the main diagonal (k=1)
upper_diag = np.diag(matrix, k=1)

print("Extracted Upper Diagonal:\n", upper_diag)
```

**Output:**
```
Extracted Upper Diagonal:
 [1 4]
```
- Extracts `[1, 4]` from the **first upper diagonal**.

Similarly, for the **lower diagonal (`k=-1`)**:

```python
# Extracting the diagonal below the main diagonal (k=-1)
lower_diag = np.diag(matrix, k=-1)

print("Extracted Lower Diagonal:\n", lower_diag)
```

**Output:**
```
Extracted Lower Diagonal:
 [2 6]
```
- Extracts `[2, 6]` from the **first lower diagonal**.

---

### 5. Summary Table

| Operation | Code Example | Output Example |
|-----------|-------------|----------------|
| Create diagonal matrix | `np.diag([1, 2, 3])` | `[[1 0 0], [0 2 0], [0 0 3]]` |
| Shift diagonal up | `np.diag([1, 2, 3], k=1)` | `[[0 1 0], [0 0 2], [0 0 0]]` |
| Shift diagonal down | `np.diag([1, 2, 3], k=-1)` | `[[0 0 0], [1 0 0], [0 2 0]]` |
| Extract main diagonal | `np.diag([[5, 1, 3], [2, 8, 4], [7, 6, 9]])` | `[5 8 9]` |
| Extract upper diagonal | `np.diag(matrix, k=1)` | `[1 4]` |
| Extract lower diagonal | `np.diag(matrix, k=-1)` | `[2 6]` |

---

### Summary:
- **`diag()`** can be used to:
  - **Create a diagonal matrix** from a 1D array.
  - **Shift the diagonal** above (`k>0`) or below (`k<0`) the main diagonal.
  - **Extract a diagonal** from a 2D matrix.
- Useful for **matrix manipulations and linear algebra applications**.
