In [1]:
import numpy as np

In [19]:
height = np.array([5.0,5.1,5.2,5.3,5.5,5.6,5.7,5.8,5.9,5.94])

In [20]:
height.mean()

5.504

In [21]:
height.std()

0.32147161616540904

In [22]:
new = height- height.mean()

In [24]:
new, height

(array([-0.504, -0.404, -0.304, -0.204, -0.004,  0.096,  0.196,  0.296,
         0.396,  0.436]),
 array([5.  , 5.1 , 5.2 , 5.3 , 5.5 , 5.6 , 5.7 , 5.8 , 5.9 , 5.94]))

In [25]:
z = new/height.std()

In [26]:
z, height

(array([-1.56779005, -1.25672059, -0.94565114, -0.63458169, -0.01244278,
         0.29862668,  0.60969613,  0.92076558,  1.23183504,  1.35626282]),
 array([5.  , 5.1 , 5.2 , 5.3 , 5.5 , 5.6 , 5.7 , 5.8 , 5.9 , 5.94]))

4.876915942691855